"""Seed data aligned with frontend INITIAL_SCENARIOS / MOCK_HISTORY."""

INITIAL_SCENARIOS = [
    {
        "id": "school",
        "name": "Go to School",
        "icon": "GraduationCap",
        "theme": {"bg": "bg-[#D0E6F0]", "text": "text-[#6B8E9B]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "s1", "text": "Student ID", "critical": True, "assignedTo": "me"},
            {"id": "s2", "text": "Homework/Essay", "critical": True, "assignedTo": "me"},
            {"id": "s3", "text": "Laptop", "critical": False, "assignedTo": "me"},
            {"id": "s4", "text": "Charger", "critical": False, "assignedTo": "me"},
            {"id": "s5", "text": "Water Bottle", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "work",
        "name": "Go to Work",
        "icon": "Briefcase",
        "theme": {"bg": "bg-[#E5E5E5]", "text": "text-[#7D7D7D]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "w1", "text": "ID Badge", "critical": True, "assignedTo": "me"},
            {"id": "w2", "text": "Smartphone", "critical": True, "assignedTo": "me"},
            {"id": "w3", "text": "Laptop & Charger", "critical": True, "assignedTo": "me"},
            {"id": "w4", "text": "Earbuds", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "gym",
        "name": "Go to Gym",
        "icon": "Dumbbell",
        "theme": {"bg": "bg-[#F4DCD6]", "text": "text-[#C08585]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "g1", "text": "Gym Card", "critical": True, "assignedTo": "me"},
            {"id": "g2", "text": "Change of Clothes", "critical": False, "assignedTo": "me"},
            {"id": "g3", "text": "Towel", "critical": False, "assignedTo": "me"},
            {"id": "g4", "text": "Water Bottle", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "camping",
        "name": "Weekend Camping",
        "icon": "Tent",
        "theme": {"bg": "bg-[#F9EBC8]", "text": "text-[#B59858]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "c1", "text": "Tent", "critical": True, "assignedTo": "me"},
            {"id": "c2", "text": "Sleeping Bag", "critical": True, "assignedTo": "me"},
            {"id": "c3", "text": "Food & Ingredients", "critical": True, "assignedTo": "me"},
        ],
    },
    {
        "id": "travel",
        "name": "Short Trip",
        "icon": "MapPin",
        "theme": {"bg": "bg-[#E0F0E3]", "text": "text-[#7A9E83]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "t1", "text": "ID Card / Passport", "critical": True, "assignedTo": "me"},
            {"id": "t2", "text": "Tickets", "critical": True, "assignedTo": "me"},
            {"id": "t3", "text": "Toiletry Bag", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "beach_day",
        "name": "Beach Day",
        "icon": "Camera",
        "theme": {"bg": "bg-[#FFE8C2]", "text": "text-[#B8843D]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "b1", "text": "Sunscreen SPF50+", "critical": True, "assignedTo": "me"},
            {"id": "b2", "text": "Swimsuit", "critical": True, "assignedTo": "me"},
            {"id": "b3", "text": "Beach Towel", "critical": False, "assignedTo": "me"},
            {"id": "b4", "text": "Flip-flops", "critical": False, "assignedTo": "me"},
            {"id": "b5", "text": "Power bank", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "library_study",
        "name": "Library Study",
        "icon": "GraduationCap",
        "theme": {"bg": "bg-[#DDEAF4]", "text": "text-[#54728A]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "l1", "text": "Student ID", "critical": True, "assignedTo": "me"},
            {"id": "l2", "text": "Laptop + Charger", "critical": True, "assignedTo": "me"},
            {"id": "l3", "text": "Notebook", "critical": False, "assignedTo": "me"},
            {"id": "l4", "text": "Highlighters", "critical": False, "assignedTo": "me"},
            {"id": "l5", "text": "Water bottle", "critical": False, "assignedTo": "me"},
        ],
    },
    {
        "id": "overnight",
        "name": "Overnight Stay",
        "icon": "Backpack",
        "theme": {"bg": "bg-[#E8E3F9]", "text": "text-[#7662B3]"},
        "type": "preset",
        "collaborators": [],
        "items": [
            {"id": "o1", "text": "ID / Wallet", "critical": True, "assignedTo": "me"},
            {"id": "o2", "text": "Phone charger", "critical": True, "assignedTo": "me"},
            {"id": "o3", "text": "Toothbrush kit", "critical": True, "assignedTo": "me"},
            {"id": "o4", "text": "Change of clothes", "critical": False, "assignedTo": "me"},
            {"id": "o5", "text": "Sleepwear", "critical": False, "assignedTo": "me"},
        ],
    },
]

MOCK_HISTORY = []
