/** Copy for Settings page only (language switch). */
export const SETTINGS_COPY = {
  en: {
    title: 'Settings',
    displayName: 'Display name',
    displayNameHint: 'Shown in Settings and on your packing avatar. Saved to your account.',
    placeholder: 'Your display name',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    signedIn: 'Signed in',
    general: 'General & Preferences',
    personalization: 'Personalization',
    accountCenter: 'Account center',
    openSection: 'Open',
    notifications: 'Notifications',
    sounds: 'Sounds & Haptics',
    autoLocation: 'Auto-Location',
    language: 'Language',
    darkMode: 'Dark Mode',
    themeColor: 'Theme Color',
    logOut: 'Log out',
    langEnglish: 'English',
    langChinese: '中文',
    pickLanguage: 'Language',
    notifDenied: 'Notifications were turned off because permission was denied.',
    close: 'Close',
    loadingPrefs: 'Saving…',
    accountSecurity: 'Account & security',
    accountSecurityHint: 'Password, login safety, and account actions',
    generalHint: 'Notifications, sounds, location, and language',
    personalizationHint: 'Dark mode and theme color',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updatePassword: 'Update password',
    passwordUpdated: 'Password updated.',
    passwordMismatch: 'New passwords do not match.',
    passwordSaveError: 'Could not update password.',
    displayNameSaveError: 'Could not save display name.',
    dangerous: 'Danger zone',
    deleteAccount: 'Delete account',
    deleteAccountHint: 'Permanently remove your lists, friends, and preferences.',
    deleteConfirmLabel: 'Type your username to confirm',
    deleteConfirmPlaceholder: 'username',
    deleteAccountButton: 'Delete my account',
    deleteMismatch: 'Username does not match.',
    serverStatus: 'API server',
    serverOk: 'Reachable',
    serverFail: 'Unreachable',
    savingProfile: 'Saving…',
    backToSettings: 'Back to settings',
  },
  zh: {
    title: '设置',
    displayName: '显示名称',
    displayNameHint: '将显示在设置与打包头像旁，并同步到账号。',
    placeholder: '输入显示名称',
    cancel: '取消',
    save: '保存',
    edit: '编辑',
    signedIn: '已登录',
    general: '通用与偏好',
    personalization: '个性化',
    accountCenter: '账号中心',
    openSection: '进入',
    notifications: '通知',
    sounds: '声音与触感',
    autoLocation: '自动定位',
    language: '语言',
    darkMode: '深色模式',
    themeColor: '主题色',
    logOut: '退出登录',
    langEnglish: 'English',
    langChinese: '中文',
    pickLanguage: '选择语言',
    notifDenied: '浏览器未授予通知权限，已关闭通知。',
    close: '关闭',
    loadingPrefs: '正在保存…',
    accountSecurity: '账号与安全',
    accountSecurityHint: '密码、登录安全与账号操作',
    generalHint: '通知、声音、定位与语言',
    personalizationHint: '深色模式与主题色',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    updatePassword: '更新密码',
    passwordUpdated: '密码已更新。',
    passwordMismatch: '两次输入的新密码不一致。',
    passwordSaveError: '无法更新密码。',
    displayNameSaveError: '无法保存显示名称。',
    dangerous: '危险操作',
    deleteAccount: '删除账号',
    deleteAccountHint: '将永久删除你的清单、好友关系与偏好设置。',
    deleteConfirmLabel: '输入用户名以确认',
    deleteConfirmPlaceholder: '用户名',
    deleteAccountButton: '删除我的账号',
    deleteMismatch: '用户名不一致。',
    serverStatus: 'API 服务',
    serverOk: '可连接',
    serverFail: '无法连接',
    savingProfile: '保存中…',
    backToSettings: '返回设置首页',
  },
};

export function settingsT(lang) {
  const L = lang === 'zh' ? SETTINGS_COPY.zh : SETTINGS_COPY.en;
  return (key) => L[key] || SETTINGS_COPY.en[key] || key;
}
