export const UI_COPY = {
  en: {
    navHome: 'Home',
    navMe: 'Me',
    loginTitle: 'CheckMate',
    loginTagline: 'Plan smarter, travel together.',
    signIn: 'Sign in',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm password',
    createAccount: 'Create account',
    pleaseWait: 'Please wait…',
    loginNeedCreds: 'Please enter username and password.',
    passwordTooShort: 'Password must be at least 6 characters.',
    passwordsNoMatch: 'Passwords do not match.',
    apiDown: 'Something went wrong. Is the API running?',
    usernameHint: '3–32 chars: lowercase letters, digits, underscore',
    passwordHintRegister: 'At least 6 characters',
    passwordHintLogin: '••••••••',
    passwordReenter: 'Re-enter password',
    greetingMorning: 'Good Morning,',
    greetingAfternoon: 'Good Afternoon,',
    greetingEvening: 'Good Evening,',
    whereToToday: 'Where to today?',
    now: 'Now',
    refreshWeather: 'Refresh weather',
    fullForecast: 'Full forecast',
    openMeteoHint: 'Open-Meteo live data · tap card for hourly & 7-day',
    quickScenarios: 'Quick Scenarios',
    myTrips: 'My Trips',
    weatherSmartTipsTitle: 'Weather smart tips',
    weatherSmartTipsDesc: 'Based on UV, humidity, wind, and temperature.',
    weatherItemsLabel: 'items',
    weatherSmartNoExtra: 'No extra weather-specific items suggested right now.',
    weatherNoTripOption: 'Create a trip first',
    weatherAddBtn: 'Add to trip',
    weatherAddOk: 'Added weather tips to your trip.',
    weatherAddFail: 'Could not add right now.',
    weatherTipsExpand: 'Show',
    weatherTipsCollapse: 'Hide',
    fromUser: 'From',
    allSet: 'All Set!',
    packedMsg: 'Everything is packed.',
    enjoyMsg: 'Enjoy the sunshine and breeze today!',
    viewHistory: 'View history',
    backHome: "Let's Go",
    lastPacked: 'Last packed',
    aiImportTitle: 'Import From AI Suggestion',
    aiImportSelectedCount: 'selected',
    aiImportSelectAll: 'Select all',
    aiImportClear: 'Clear',
    aiImportMust: 'Must',
    aiImportNice: 'Nice',
    aiImportNewTripPlaceholder: 'New trip name',
    aiImportCreateBtn: 'Create trip with selected items',
    aiImportNoEditableTrips: 'No editable trips',
    aiImportAddBtn: 'Add to existing',
    aiImportOpenTrips: 'Go to my Trips',
    aiImportCreatedOk: 'Created a new trip with {count} items.',
    aiImportAddedOk: 'Added {count} items to selected trip.',
    aiImportCreateFail: 'Could not create a trip right now.',
    aiImportAddFail: 'Could not add items right now.',
  },
  zh: {
    navHome: '首页',
    navMe: '我的',
    loginTitle: 'CheckMate',
    loginTagline: '更聪明地计划，一起出行。',
    signIn: '登录',
    register: '注册',
    username: '用户名',
    password: '密码',
    confirmPassword: '确认密码',
    createAccount: '创建账号',
    pleaseWait: '请稍候…',
    loginNeedCreds: '请输入用户名和密码。',
    passwordTooShort: '密码至少 6 位。',
    passwordsNoMatch: '两次输入的密码不一致。',
    apiDown: '请求失败：请确认后端 API 已启动。',
    usernameHint: '3–32 位：小写字母/数字/下划线',
    passwordHintRegister: '至少 6 位',
    passwordHintLogin: '••••••••',
    passwordReenter: '再次输入密码',
    greetingMorning: '早上好，',
    greetingAfternoon: '下午好，',
    greetingEvening: '晚上好，',
    whereToToday: '今天去哪儿？',
    now: '当前',
    refreshWeather: '刷新天气',
    fullForecast: '完整预报',
    openMeteoHint: 'Open-Meteo 实时数据 · 点击卡片查看 24 小时与 7 天游',
    quickScenarios: '快捷清单',
    myTrips: '我的行程',
    weatherSmartTipsTitle: '天气打包建议',
    weatherSmartTipsDesc: '基于紫外线、湿度、风速和温度自动生成。',
    weatherItemsLabel: '条',
    weatherSmartNoExtra: '当前没有额外的天气相关建议。',
    weatherNoTripOption: '请先创建行程',
    weatherAddBtn: '加入行程',
    weatherAddOk: '已将天气建议加入你的行程。',
    weatherAddFail: '暂时无法添加，请稍后重试。',
    weatherTipsExpand: '展开',
    weatherTipsCollapse: '收起',
    fromUser: '来自',
    allSet: '准备就绪！',
    packedMsg: '已全部打包完成。',
    enjoyMsg: '祝你一路顺风！',
    viewHistory: '查看历史',
    backHome: '回到首页',
    lastPacked: '最近完成',
    aiImportTitle: '从 AI 建议导入',
    aiImportSelectedCount: '已选',
    aiImportSelectAll: '全选',
    aiImportClear: '清空',
    aiImportMust: '必带',
    aiImportNice: '可选',
    aiImportNewTripPlaceholder: '新建 Trip 名称',
    aiImportCreateBtn: '新建 Trip 并导入所选条目',
    aiImportNoEditableTrips: '暂无可编辑 Trips',
    aiImportAddBtn: '添加到现有',
    aiImportOpenTrips: '去我的 Trips 查看',
    aiImportCreatedOk: '创建成功，已新建 Trip 并导入 {count} 条。',
    aiImportAddedOk: '添加成功，已导入 {count} 条到所选 Trip。',
    aiImportCreateFail: '创建失败，请稍后再试。',
    aiImportAddFail: '添加失败，请稍后再试。',
  },
};

export function uiT(lang) {
  const L = lang === 'zh' ? UI_COPY.zh : UI_COPY.en;
  return (key) => L[key] || UI_COPY.en[key] || key;
}

